version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: redis
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - py-dependencies-{{ checksum "requirements.txt" }}
      - run: python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: py-dependencies-{{ checksum "requirements.txt" }}
      - run: mkdir test-reports
      - run: . venv/bin/activate && pytest --cov-report xml:test-reports/coverage.xml --cov=riberry ./tests
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
