version: 2
jobs:
  backend:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - py-dependencies-{{ checksum "requirements.txt" }}
      - run: python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: py-dependencies-{{ checksum "requirements.txt" }}
      - run: . venv/bin/activate && pytest --cov=riberry ./tests

  frontend:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - nd-dependencies-{{ checksum "./riberry-web/package.json" }}
      - run: cd ./riberry-web && yarn install
      - save_cache:
          paths:
            - ./riberry-web/node_modules
          key: nd-dependencies-{{ checksum "./riberry-web/package.json" }}
      - run: cd ./riberry-web && yarn test

workflows:
  version: 2
  frontend_backend:
    jobs:
      - frontend
      - backend