from .base import BasePermissionDomain


class FormDomain(BasePermissionDomain):
    PERM_JOB_READ_SELF = 'JOB_READ_SELF'
    PERM_JOB_CREATE_SELF = 'JOB_CREATE_SELF'
    PERM_JOB_UPDATE_SELF = 'JOB_UPDATE_SELF'
    PERM_JOB_DELETE_SELF = 'JOB_DELETE_SELF'
    PERM_JOB_EXECUTE_SELF = 'JOB_EXECUTE_SELF'
    PERM_JOB_SCHEDULE_SELF = 'JOB_SCHEDULE_SELF'
    PERM_JOB_READ = 'JOB_READ'
    PERM_JOB_CREATE = 'JOB_CREATE'
    PERM_JOB_UPDATE = 'JOB_UPDATE'
    PERM_JOB_DELETE = 'JOB_DELETE'
    PERM_JOB_EXECUTE = 'JOB_EXECUTE'
    PERM_JOB_SCHEDULE = 'JOB_SCHEDULE'
    PERM_JOB_PRIORITIZE = 'JOB_PRIORITIZE'
    PERM_APP_SCHEDULES_READ = 'APP_SCHEDULES_READ'
    PERM_APP_SCHEDULES_READ_BUILTIN = 'APP_SCHEDULES_READ_BUILTIN'


class ApplicationDomain(BasePermissionDomain):
    PERM_APP_SCHEDULES_MANAGE = 'APP_SCHEDULES_MANAGE'


class SystemDomain(BasePermissionDomain):
    PERM_CAPACITY_CONFIG_MANAGE = 'CAPACITY_CONFIG_MANAGE'
