[celery]

result_backend = 'redis://'
broker_url = 'redis://'


[background.events]

limit = 1000
interval = 2


[background.schedules]

interval = 5


[background.capacity]

interval = 5


[database.connection]

envvar = "RIBERRY_DATABASE_URL"
echo = false


[database.arguments]

timeout = 60


[policies]

provider = "default"


[authentication.providers]

supported = ["default", "ldap"]
default = "default"


[authentication.token]

provider = "jwt"
envvar = "RIBERRY_AUTHENTICATION_SECRET"


[authentication.ldap]

server = "..."
ssl = true
interval = 120


[authentication.ldap.credentials]

envvar = "RIBERRY_LDAP_CREDENTIALS"


[authentication.ldap.user]

searchPath = "..."
class = "user"


[authentication.ldap.user.attributes]

uniqueName = "sAMAccountName"
distinguishedName = "distinguishedName"
membership = "memberOf"


[authentication.ldap.user.attributes.additional]

firstName = "givenName"
lastName = "sn"
displayName = "displayName"
email = "mail"
department = "department"


[authentication.ldap.group]

searchPath = "..."
class = "group"
extraFilter = "(sAMAccountName=*)"


[authentication.ldap.group.attributes]

uniqueName = "sAMAccountName"
distinguishedName = "distinguishedName"
membership = "memberOf"


[authentication.ldap.group.attributes.additional]

label = "name"
description = "description"


[notification.email]

enabled = false
smtpServer = "..."
sender = "noreply@example.com"

